#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ren980602@gmail.com
#    password: Renan62.29
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
server:
  port: ${PORT:8080}   # Railway 会注入 PORT，默认用 8080

spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: ${SPRING_MAIL_STARTTLS:true}  # 对应 587
      mail.smtp.ssl.enable: ${SPRING_MAIL_SSL:false}           # 对应 465

