server:
  port: ${PORT:8080}

spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${SPRING_MAIL_STARTTLS:true}
          ssl:
            enable: ${SPRING_MAIL_SSL:false}


