server:
  port: ${PORT:8080}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ren980602@gmail.com   # 你的 Gmail
    password: ilhgjybtsegojpsd      # 你的应用专用密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false




